### ISSUE TITLE
psconfig validate return code issue

### ISSUE THREAD

**Issue by apertome** [perfsonar/psconfig#72]
We are seeing an issue with `psconfig validate` status codes, when called from a script.

When running `psconfig validate http://pwa-dev3.grnoc.iu.edu/pwa/pub/config/iperf3-1?format=psconfig` manually, it validates.

```
[mj82@mca-dev ~]$ node test-node-exec.js


>>> STDOUT <<<
stdout Loading template ...... OK
Validating JSON schema ...... OK
Verifying object references ...... OK

>>> END STDOUT <<<




stderr [Mon Jul 22 19:15:26 2019] pScheduler Validation (Quick):   0%
[Mon Jul 22 19:15:27 2019] pScheduler Validation (Quick):  50%
[Mon Jul 22 19:15:28 2019] pScheduler Validation (Quick): 100%
[Mon Jul 22 19:15:28 2019] pScheduler Validation (Quick): 100%
progress bar already finished at /usr/lib/perfsonar/bin/psconfig_commands/validate line 520.





err { Error: Command failed: /usr/bin/psconfig validate  http://pwa-dev3.grnoc.iu.edu/pwa/pub/config/iperf3-1?format=psconfig
[Mon Jul 22 19:15:26 2019] pScheduler Validation (Quick):   0%
[Mon Jul 22 19:15:27 2019] pScheduler Validation (Quick):  50%
[Mon Jul 22 19:15:28 2019] pScheduler Validation (Quick): 100%
[Mon Jul 22 19:15:28 2019] pScheduler Validation (Quick): 100%
progress bar already finished at /usr/lib/perfsonar/bin/psconfig_commands/validate line 520.

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
  killed: false,
  code: 255,
  signal: null,
  cmd: '/usr/bin/psconfig validate  http://pwa-dev3.grnoc.iu.edu/pwa/pub/config/iperf3-1?format=psconfig' }




errror code is255
```

Adding the `-q` flag fixes this, but it's not always practical since you can't see the actual stdout/stderr values then.

**Comment by arlake228** [comment]
Added a line that silences the progress bar if there is no tty attached. This seems to fix the issue.
